"use client";

import { useState } from "react";

interface Claim {
    providerName: string;
    service: string;
    billedAmount: string;
    allowedAmount: string | null;
    insurancePaid: string | null;
    copayAmount: string | null;
    appliedTowardsDeductible: string | null;
    coinsuranceAmount: string | null;
    otherAmount: string | null;
    otherAmountReason: string | null;
    patientResponsibility: string | null;
}

interface AIClaimExplanationProps {
    claim: Claim;
}

interface ExplainClaimResponse {
    explanation?: string;
    error?: string;
}

/**
 * Displays an AI-generated explanation of a claim's cost breakdown.
 * Sends the claim data to the /api/ai/explain-claim API route when requested by the user.
 */
function AIClaimExplanation({ claim }: AIClaimExplanationProps) {
    const [explanation, setExplanation] = useState("");
    const [error, setError] = useState("");
    const [isLoading, setIsLoading] = useState(false);

    // Handles the button click to request an AI-generated explanation
    async function handleGenerateExplanation() {
        setError("");
        setIsLoading(true);

        // Make a POST request to the API route with the claim data
        try {
            const response = await fetch("/api/ai/explain-claim",
                {
                    method: "POST",
                    headers: { "Content-Type": "application/json", },
                    body: JSON.stringify({ claim }),
                }
            );

            const data = (await response.json()) as ExplainClaimResponse;

            if (!response.ok) {
                throw new Error(
                    data.error ??
                    "Unable to generate an AI explanation.");
            }

            if (!data.explanation) {
                throw new Error(
                    "The API did not return an explanation."
                );
            }

            setExplanation(data.explanation);
        } catch (error) {
            const message = error instanceof Error ? error.message : "Something went wrong while generating the explanation.";
            setError(message);
        } finally {
            setIsLoading(false);
        }
    }

    return (
        <section className="rounded-2xl border bg-white p-6 shadow-sm">
            <div>
                <h2 className="text-xl font-semibold">AI Claim Explanation</h2>
                <p className="mt-1 text-sm text-gray-600">Generate a conversational explanation of this claim's cost breakdown.</p>
            </div>

            <button
                type="button"
                onClick={handleGenerateExplanation}
                disabled={isLoading}
                className="mt-4 rounded-lg bg-blue-600 px-4 py-2 font-medium text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-60"
            >
                {isLoading ? "Generating explanation..." : explanation ? "Regenerate explanation" : "Explain with AI"}
            </button>

            {error && (<div role="alert" className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>
            )}

            {explanation && (
                <div className="mt-5 rounded-xl bg-gray-50 p-4">
                    <h3 className="font-semibold">Generated explanation</h3>

                    <div className="mt-3 whitespace-pre-line text-gray-700">{explanation}</div>

                    <p className="mt-4 text-xs text-gray-500">
                        This explanation was generated by AI and may contain errors. Review your explanation of benefits or contact your insurance provider for clarification.
                    </p>
                </div>
            )}
        </section>
    );
}

export default AIClaimExplanation;
